### PR TITLE
Inject Style via JS

### PR DESCRIPTION
**Pull request by shshaw**
Negate the need for an external CSS inclusion :-)

### CODE REVIEW

**Comment by shshaw** [comment]
Demo: http://codepen.io/shshaw/pen/b591a6ee248a9fcab578bf038a5a4d15?editors=0010

For reference, I used http://refresh-sf.com/ to minify the CSS quickly

**Comment by sdras** [comment]
I LOVE the style injection, especially after running some perf tests to make sure it didn't impact the player. Nice work, Shaw.

**Comment by sdras** [comment]
I'll go in and remove the CSS file and fix up the readme, dependent on this change.

**Comment by shshaw** [comment]
Apologies for not updating the README. As soon as you accepted the pull
request I remembered that.

Might want to keep the CSS file just to have a clean, non-minified CSS file
to edit.

**Comment by sdras** [comment]
Yep, I realized that as soon as I was working on it. I kept the CSS intact, but the readme specifically denotes that you don't need it. Eventually I'll put in a better build system so there's a separate minified file and directory.

**Pull request merged**
